[package]
name = "bi_sign_core"
version = "1.0.0"
edition = "2021"

authors = ["Perondas <thomas@perondas.dev>"]

[dependencies]
anyhow = "1.0.98"
rsa = "0.9.8"
sha1 = "0.10.6"
binrw = "0.15.0"
nutype = "0.6.1"
rand = "0.8.5"
